foo = ['a', 'b', 'c']
print(foo[3])      # will this result in an error?

print('Yes, error because out of range')